[files]
extend-exclude = [
    "*.json",
    "*.js",
    "*.ipynb",
    "llm-finetuning/*",
    "end-to-end-computer-vision/*",
    "research-radar/data/*.jsonl",
]

[default.extend-identifiers]
HashiCorp = "HashiCorp"
NDArray = "NDArray"
K_Scatch = "K_Scatch"
MCAGA1UECgwZQW1hem9uIFdlYiBTZXJ2aWNlcywgSW5jLjETMBEGA1UECwwKQW1h = "MCAGA1UECgwZQW1hem9uIFdlYiBTZXJ2aWNlcywgSW5jLjETMBEGA1UECwwKQW1h"
VQQGEwJVUzEQMA4GA1UEBwwHU2VhdHRsZTETMBEGA1UECAwKV2FzaGluZ3RvbjEi = "VQQGEwJVUzEQMA4GA1UEBwwHU2VhdHRsZTETMBEGA1UECAwKV2FzaGluZ3RvbjEi"
MDEyOk9yZ2FuaXphdGlvbjg4Njc2OTU1 = "MDEyOk9yZ2FuaXphdGlvbjg4Njc2OTU1"

[default.extend-words]
# Don't correct the surname "Teh"
preprocesser = "preprocesser"
Preprocesser = "Preprocesser"
aks = "aks"
hashi = "hashi"
womens = "womens"
prepend = "prepend"
prepended = "prepended"
goes = "goes"
bare = "bare"
prepending = "prepending"
prev = "prev"
creat = "creat"
ret = "ret"
daa = "daa"
arange = "arange"
cachable = "cachable"
OT = "OT"
cll = "cll"
Louvre = "Louvre"
quantised = "quantised"
colours = "colours"
initialised = "initialised"
visualisation = "visualisation"
customise = "customise"
modernbert = "modernbert"
deepseek = "deepseek"
huggingface = "huggingface"
answerdotai = "answerdotai"
preprocessor = "preprocessor"
logits = "logits"
analyse = "analyse"
Labour = "Labour"
# Forecasting and statistical terms
MAPE = "MAPE"
mape = "mape"
yhat = "yhat"
yhat_lower = "yhat_lower"
yhat_upper = "yhat_upper"

[default]
locale = "en-us"
