[files]
extend-exclude = ["*.csv", "sign-language-detection-yolov5/*", "orbit-user-analysis/steps/report.py", "customer-satisfaction/pipelines/deployment_pipeline.py", "customer-satisfaction/streamlit_app.py", "nba-pipeline/Building and Using An MLOPs Stack With ZenML.ipynb", "customer-satisfaction/tests/data_test.py"]

[default.extend-identifiers]
#  HashiCorp = "HashiCorp"
connexion = "connexion"
preprocesser = "preprocesser"
Preprocesser = "Preprocesser"

[default.extend-words]
#  aks = "aks"
GOES = "GOES"
lenght = "lenght"
preprocesser = "preprocesser"
Preprocesser = "Preprocesser"
Implicitly = "Implicitly"

[default]
locale = "en-us"
