enable_cache: False

settings:
  docker:
    required_integrations:
      - mlflow

# configuration of the Model Control Plane
model_version:
  name: Customer_Satisfaction_Predictor
  license: Apache 2.0
  description: Predictor of Customer Satisfaction.
  tags: ["classification", "customer_satisfaction"]