# environment configuration
settings:
  docker:
    required_integrations:
      - sklearn

# configuration of the Model Control Plane
model:
  name: breast_cancer_classifier
  license: Apache 2.0
  description: Classification of Breast Cancer Dataset.
  tags: ["classification", "sklearn"]
