# environment configuration
settings:
  docker:
    required_integrations:
      - sklearn
    requirements:
      - pyarrow

# configuration of the Model Control Plane
model_version:
  name: breast_cancer_classifier
  license: Apache 2.0
  description: Classification of Breast Cancer Dataset.
  tags: ["classification", "sklearn"]

steps:
  model_trainer:
    settings:
      step_operator.sagemaker:
        estimator_args: 
          instance_type: "ml.m5.large"
