# environment configuration
settings:
  docker:
    requirements:
      - ratelimit
      - pgvector
      - psycopg2-binary
      - beautifulsoup4
      - unstructured
      - pandas
      - numpy
      - sentence-transformers>=3
      - transformers==4.43.1
      - litellm
      - ollama
      - tiktoken
      - umap-learn
      - matplotlib
      - pyarrow
      - rerankers[flashrank]
      - datasets
      - torch
      - distilabel
      - argilla
      - pygithub
      - openai
    environment:
      ZENML_PROJECT_SECRET_NAME: llm_complete
    python_package_installer: "uv"

parameters:
  use_argilla: false